/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as SeriesSlugRouteImport } from './routes/series/$slug'
import { Route as RssSplatRouteImport } from './routes/rss/$'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RssSplatRoute = RssSplatRouteImport.update({
  id: '/rss/$',
  path: '/rss/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/rss/$': typeof RssSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/rss/$': typeof RssSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/posts': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/rss/$': typeof RssSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/$'
    | '/posts/$slug'
    | '/rss/$'
    | '/series/$slug'
    | '/posts/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/$'
    | '/posts/$slug'
    | '/rss/$'
    | '/series/$slug'
    | '/posts'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/$'
    | '/posts/$slug'
    | '/rss/$'
    | '/series/$slug'
    | '/posts/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PostsSlugRoute: typeof PostsSlugRoute
  RssSplatRoute: typeof RssSplatRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/$': {
      id: '/rss/$'
      path: '/rss/$'
      fullPath: '/rss/$'
      preLoaderRoute: typeof RssSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  PostsSlugRoute: PostsSlugRoute,
  RssSplatRoute: RssSplatRoute,
  SeriesSlugRoute: SeriesSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
